# Generated by Django 6.0.1 on 2026-03-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message_html', models.TextField(help_text='HTML content for the email body')),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=500)),
                ('cc_emails', models.CharField(blank=True, default='', max_length=500)),
                ('bcc_emails', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('message_html', models.TextField()),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
    ]
